image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1100.6374 ,    0.     ,  654.09269,
            0.     , 1075.6952 ,  498.56487,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.424491, -0.028871, -0.052745, -0.001152, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1099.77759,    0.     ,  653.58173,    0.     ,
            0.     , 1074.20117,  497.87242,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
