image_width: 800
image_height: 600
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [772.2922 ,   0.     , 393.95253,
           0.     , 773.65839, 315.10823,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.270183, -0.107077, -0.004193, 0.001556, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [693.01105,   0.     , 393.02415,   0.     ,
           0.     , 735.58319, 314.57737,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
